name: RDS Maintenance Bot

on:
  schedule:
    # 15:00 UTC = 20:30 IST (8:30 PM)
    # 0=Sunday, 3=Wednesday
    - cron: '*/5 * * * *'
  
  # Defines a button to run manually for testing
  workflow_dispatch:

jobs:
  run-maintenance-bot:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Boto3
        run: pip install boto3

      - name: Run Script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python main.py
